### PR TITLE
fix: sending images to the vscode extension fails, if the tensor is not local to the cpu

### PR DESCRIPTION
**Pull request by WinPlay02**
Related-to: https://github.com/Safe-DS/DSL/pull/954 (the PR requires this fix to work)

Fixes the following error: 

`RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending.`

This error only occurs on systems that support graphics acceleration of tensor operations. 
On other systems, the tensor is local to the CPU by default and does not need to be converted.
The conversion process is a noop, if the tensor is already local to the CPU.

### CODE REVIEW

**Comment by WinPlay02** [comment]
@SmiteDeluxe The PR for the fix we talked about

**Review by lars-reimann — DISMISSED** [review]
The code looks good. I cannot currently verify, though, whether this fixes the issue. Still, feel free to merge if you've checked this.

**Comment by WinPlay02** [comment]
> The code looks good. I cannot currently verify, though, whether this fixes the issue. Still, feel free to merge if you've checked this.

As I'm not affected by this, @SmiteDeluxe would be able to verify and merge this

**Review by SmiteDeluxe — APPROVED** [review]
Working for me with this change!

**Pull request merged**
