### PR TITLE
feat: cleaner public api

### LINKED ISSUE #53: Cleaner public API
### Is your feature request related to a problem?

Currently, all declarations reside in public modules (file names have no leading underscore), even though most are only needed internally. Moreover, the functions used by the [DSL](https://github.com/Safe-Ds/DSL) for code generation are nested deeply, which leads to long imports and calls and ultimately badly readable code:

```
f((safeds_runner.server.pipeline_manager.runner_memoized_function_call("tests.generator.infixOperation.h", h, [], [])) < (safeds_runner.server.pipeline_manager.runner_memoized_function_call("tests.generator.infixOperation.h", h, [], [])))
```

### Desired solution

1. Make everything internal that does not need to be used from the outside.
2. Simplify usages of functions that are needed from the outside:
    - `safeds_runner.server.pipeline_manager.runner_memoized_function_call` -> `safeds_runner.memoized_call`
    - `safeds_runner.server.pipeline_manager.runner_save_placeholder` -> `safeds_runner.save_placeholder`
    - `safeds_runner.server.pipeline_manager.runner_filemtime` -> `safeds_runner.file_mtime`.

    This can be done by a) renaming functions to the desired name and b) adding imports to `__init__` files. The functions need not be moved.

### Possible alternatives (optional)

_No response_

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by lars-reimann**
Closes #53

### Summary of Changes

Define a small public interface consisting of
* `safeds_runner.file_mtime`,
* `safeds_runner.memoized_call`,
* `safeds_runner.save_placeholder`.

These are used by the code generator of the [DSL](https://github.com/Safe-DS/DSL).

### CODE REVIEW

**Comment by lars-reimann** [comment]
@WinPlay02 Would you mind reviewing this?

**Comment by lars-reimann** [comment]
It's also quite interesting that when I also add `start_server` to `src/safeds_runner/__init__.py`, the runtime of the tests increases from roughly 15s to 33s, apparently due to the imports of `Image` and `Table` in `src/safeds_runner/server/_json_encoder.py`.

**Review by WinPlay02 — APPROVED** [review]
Should be good to merge

**Pull request merged**
