### PR TITLE
feat: prepare and pool processes

### LINKED ISSUE #85: Improve startup time of workers
During evaluation, we observed delays ranging from 3s to 20s+ between a program message and the first values coming back, regardless of the size of the data. For better usability, this time should be reduced as much as possible, since this 

* delays the table view showing up 
* and later causes another delay for the profiling.

### PR DESCRIPTION
**Pull request by WinPlay02**
Closes #85

### Summary of Changes

- Use a process pool to keep started processes waiting
- The max. amount of pipeline processes is now set to `4`.
- Reuse started processes. This should be correct, as the same pipeline process cannot be used by multiple pipelines at the same time. As the `metapath` is reset to remove the custom generated Safe-DS pipeline code, only global library imports (and settings) should remain. If this is a concern, `maxtasksperchild` can be set to `1`, in which case pipeline processes are not reused.
- Reuse shared memory location for saving placeholders, if the memoization infrastructure has added such a location to the object being saved

### CODE REVIEW

**Comment by lars-reimann** [comment]
> The max. amount of pipeline processes is now set to the amount of available CPU cores.

We probably don't need that many:

image

Most of the time, the processes will idle. As long as the runner is local, 2 workers should be enough. I don't think the user would fire off pipeline runs without waiting for completion of the previous one.

**Comment by WinPlay02** [comment]
> Most of the time, the processes will idle. As long as the runner is local, 2 workers should be enough. I don't think the user would fire off pipeline runs without waiting for completion of the previous one.

I see, that's a lot of memory wasted. But two processes are easily saturated, if two tables are opened in the EDA view (waiting for stats). A normal execution would only be queued and needs to wait for any running pipelines to complete first.
The statistical analysis of the EDA view does another pipeline execution after the table has been fetched, according to my observations.
I'd say 4 would probably be a good middle ground to limit the processes to.

**Comment by WinPlay02** [comment]
Also, coverage seems broken again. It doesn't seem to like multiprocessing pools very much.

**Comment by lars-reimann** [comment]
> I'd say 4 would probably be a good middle ground to limit the processes to.

Sure, seems good to me. Can easily be tweaked later.

**Comment by lars-reimann** [comment]
> Also, coverage seems broken again. It doesn't seem to like multiprocessing pools very much.

I would not consider this a blocker for this PR. I'll investigate whether that can be fixed later.

**Comment by WinPlay02** [comment]
> But then the original worker is already free again, no?

When viewing one table, then this is true. But everything would break, as soon as two tables are waiting for stats. This might be too cautious, but since gathering the stats for the EDA view takes a bit of time, this could be irritating.

**Comment by lars-reimann** [comment]
> But everything would break, as soon as two tables are waiting for stats.

Break in what way?

**Comment by WinPlay02** [comment]
> > But everything would break, as soon as two tables are waiting for stats.
> 
> Break in what way?

Maybe break is not the right description. 
Manual executions wait for as long as stats and plots are being calculated. For large tables, this can take some time.
As a user, I'd think something broke, as nothing (obvious) is happening anymore.

**Comment by lars-reimann** [comment]
> > > But everything would break, as soon as two tables are waiting for stats.
> > 
> > 
> > Break in what way?
> 
> Maybe break is not the right description. Manual executions wait for as long as stats and plots are being calculated. For large tables, this can take some time. As a user, I'd think something broke, as nothing (obvious) is happening anymore.

I see, that's an issue for another day (and someone else 😉).

**Comment by WinPlay02** [comment]
This PR should lead to a modest improvement in startup time, and a small improvement (mostly depending on the content) in runtime.

I don't know what the target is, and how much potential for startup-optimization is left, but I was able to get small and medium tables after a few 100ms, after pressing the "Explore" lens.

**Comment by lars-reimann** [comment]
> This PR should lead to a modest improvement in startup time, and a small improvement (mostly depending on the content) in runtime.
> 
> I don't know what the target is, and how much potential for startup-optimization is left, but I was able to get small and medium tables after a few 100ms, after pressing the "Explore" lens.

It already feels *a lot* better. The last idea I'd have is to add an initializer to the process pool doing something like

```
def _init():
    from safeds.data.tabular.containers import Table

    Table()
```

Then all processes can immediately display a `Table`.

**Comment by lars-reimann** [comment]
There seems to be an issue with the memoization of block & expression lambdas now:

```
package test

pipeline whoSurvived {
    val titanic = Table
        .fromCsvFile("titanic.csv")
        .removeColumns(["id", "ticket", "cabin", "port_embarked", "fare"]);

    val filtered = titanic.filterRows((row) ->
        row.getValue("age") as Float <= 100
    );
}
```

If you change the `100` and explore `filtered` a couple of times, you eventually stop getting updates.

**Comment by WinPlay02** [comment]
> There seems to be an issue with the memoization of block & expression lambdas now:
> 
> ```
> package test
> 
> pipeline whoSurvived {
>     val titanic = Table
>         .fromCsvFile("titanic.csv")
>         .removeColumns(["id", "ticket", "cabin", "port_embarked", "fare"]);
> 
>     val filtered = titanic.filterRows((row) ->
>         row.getValue("age") as Float <= 100
>     );
> }
> ```
> 
> If you change the `100` and explore `filtered` a couple of times, you eventually stop getting updates.

I can't reproduce this right now (but I'm seeing another somewhat related error, `Error during pipeline execution: Document not found`, during exploration).
I suppose this is the problem from above, that exploring causes stats collection to fill up all available pipeline processes, which causes everything after that to stall.
Considering that, I don't know what about the lambdas would be special to break the memoization/runner.

**Comment by lars-reimann** [comment]
I've started looking into this a little:  It seems like `inspect.getsource` itself returns outdated values. I've also had it throw an exception after changing the pipeline file:

```
2024-04-21 21:00:18.067 [debug] [Runner] [9fd84cfe-e31c-4201-b80f-86cef175ae0a] lineno is out of bounds
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_pipeline_manager.py line 298
	at <frozen runpy> line 226
	at <frozen runpy> line 98
	at <frozen runpy> line 88
	at demo/gen_titanic_example3 line 4
	at demo/gen_titanic line 19 (mapped to 'titanic.sds' line 7)
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_pipeline_manager.py line 419
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_memoization_map.py line 146
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_memoization_utils.py line 396
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_memoization_utils.py line 343
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_memoization_utils.py line 343
	at E:\Repositories\safe-ds\Runner\src\safeds_runner\server\_memoization_utils.py line 345
	at C:\Users\Lars\AppData\Local\Programs\Python\Python312\Lib\inspect.py line 1282
	at C:\Users\Lars\AppData\Local\Programs\Python\Python312\Lib\inspect.py line 1264
	at C:\Users\Lars\AppData\Local\Programs\Python\Python312\Lib\inspect.py line 1128
```

**Comment by lars-reimann** [comment]
Looks like [this Python bug](https://bugs.python.org/issue1218234) is back. Got it working now 🎉.

**Review by lars-reimann — APPROVED** [review]
Execution time feels great now, awesome stuff!

**Comment by WinPlay02** [comment]
Thanks for investigating further, and great that it is now working 🎉

**Pull request merged**
