### PR TITLE
fix: race condition when initializing multiprocessing manager

### LINKED ISSUE #18: Possible deadlock while running tests
### Describe the bug

I had to cancel [this test run (Python 3.12)](https://github.com/Safe-DS/Runner/actions/runs/7052137413/job/19196553722) after 5 minutes:

image

The second attempt succeeded just fine, but still shows a deprecation warning, which is likely related to the issue:

```txt
   /opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=1909) is multi-threaded, use of fork() may lead to deadlocks in the child.
    self.pid = os.fork()
```

### To Reproduce

1. Run `test_should_execute_pipeline_return_valid_placeholder` repeatedly
2. Eventually, the process gets stuck in `wait_for_messages`.

### Expected behavior

Tests should always run through. As an extra safeguard, we might want to limit the runtime of some "dangerous" tests and fail them after x seconds. This can be done using [`pytest-timeout`](https://github.com/pytest-dev/pytest-timeout#the-timeout-marker-api).

### Screenshots (optional)

_No response_

### Additional Context (optional)

This issue also occurred in [this run](https://github.com/Safe-DS/Runner/actions/runs/7051993368/job/19196083623).

### PR DESCRIPTION
**Pull request by WinPlay02**
Closes #18

### Summary of Changes

- use spawn instead of fork to not deadlock when running tests

### CODE REVIEW

**Comment by lars-reimann** [comment]
The process seems to get stuck inside `wait_for_messages` when running the test

**Comment by WinPlay02** [comment]
That's true, but this does not seem to be the (main) problem. The main process gets stuck there because it doesn't receive any messages from the pipeline process.

This seems to be related to a race condition when initializing the message queue.
The problem occurred because the fields were changed to cached properties. (https://docs.python.org/3.12/library/functools.html#functools.cached_property)
While cached properties were locked in Python 3.11 to ensure they only get assigned once, they are no longer in Python 3.12.

Note: 
> Changed in version 3.12: Prior to Python 3.12, cached_property included an undocumented lock to ensure that in multi-threaded usage the getter function was guaranteed to run only once per instance. However, the lock was per-property, not per-instance, which could result in unacceptably high lock contention. In Python 3.12+ this locking is removed.

This caused the multiprocessing manager to sometimes be initialized twice (instead of only once), and the main process would get a different queue than the pipeline process.

Because no messages were sent to the correct queue, the main process waited indefinitely for results.

I confirmed this working under WSL2 with Python 3.12 (or I was incredibly lucky, and no problem has happened since I made the change).

So in the end, there was no deadlock (according to this debugging results), and the fork deprecation message turned out to be a red herring. Although, forking in a threaded program is still bad practice and should be avoided (and is also removed in this PR).

**Comment by WinPlay02** [comment]
@SmiteDeluxe This should also fix the issue, that the extension sometimes isn't notified of the current pipeline execution progress

**Review by lars-reimann — APPROVED** [review]
I can no longer reproduce #18. Thanks for the fix.

**Pull request merged**
